# Generated by Django 3.2.5 on 2021-08-03 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('treatment', '0004_auto_20210730_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicinesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RequestMedicinesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.medicinesmodel')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.requestsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorMedicinesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(max_length=200, null=True)),
                ('habbit', models.CharField(max_length=200, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='users.doctormodel')),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.medicinesmodel')),
            ],
        ),
    ]
