# Generated by Django 3.2.5 on 2021-08-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('treatment', '0005_doctormedicinesmodel_medicinesmodel_requestmedicinesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecautionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='doctormedicinesmodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctormodel'),
        ),
        migrations.CreateModel(
            name='RequestPrecautionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precaution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.precautionmodel')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.requestsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPrecautionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctormodel')),
                ('precaution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.precautionmodel')),
            ],
        ),
    ]
